<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example</groupId>
    <artifactId>coding-technology-examples</artifactId>
    <version>0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Coding Technology Examples</name>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <maven.compiler.release>25</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <pragmatica.version>0.8.3</pragmatica.version>
    </properties>

    <modules>
        <module>usecase-userlogin-sync</module>
        <module>usecase-userlogin-async</module>
        <module>usecase-internal-service</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.pragmatica-lite</groupId>
                <artifactId>core</artifactId>
                <version>${pragmatica.version}</version>
            </dependency>
            <dependency>
                <groupId>org.pragmatica-lite</groupId>
                <artifactId>jackson</artifactId>
                <version>${pragmatica.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>

